package com.hogar.seguro.service;

import com.hogar.seguro.dto.ApplicationDto;
import com.hogar.seguro.exception.ResourceNotFoundException;
import com.hogar.seguro.model.Application;
import com.hogar.seguro.model.Resident;
import com.hogar.seguro.repository.ApplicationRepository;
import com.hogar.seguro.repository.ResidentRepository;
import jakarta.transaction.Transactional;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Service
public class ApplicationService {

    private final ApplicationRepository applicationRepository;
    private final ResidentRepository residentRepository;//relationShip with resident

    public ApplicationService(ApplicationRepository applicationRepository,
                              ResidentRepository residentRepository) {
        this.applicationRepository = applicationRepository;
        this.residentRepository = residentRepository;
    }


//-------Mapping Logic:------------

    //1. DTO -> Entity
    public Application toEntity(ApplicationDto dto) {
        Application application = new Application();
        application.setName(dto.getName());
        application.setEmail(dto.getEmail());
        application.setPhoneNumber(dto.getPhoneNumber());
        application.setMessage(dto.getMessage());
        application.setType(dto.getApplicationType());

            //relationShip logic:
        if (dto.getResidentId() != null) {
            Resident resident = residentRepository.findByIdAndActiveTrue(dto.getResidentId())
                    .orElseThrow(() -> new ResourceNotFoundException("Resident with id " + dto.getResidentId() + " not found."));
            application.setResident(resident);
        }

           //generated by system:
        application.setCreatedAt(LocalDateTime.now());
        return application;
    }


    //2. Entity -> DTO
    public ApplicationDto toDto(Application application) {
        ApplicationDto dto = new ApplicationDto();
        dto.setId(application.getId());
        dto.setName(application.getName());
        dto.setEmail(application.getEmail());
        dto.setPhoneNumber(application.getPhoneNumber());
        dto.setMessage(application.getMessage());
        dto.setApplicationType(application.getType());
        dto.setCreatedAt(application.getCreatedAt()); //for admin

            //if relationship exists, save id
        if (application.getResident() != null) {
            dto.setResidentId(application.getResident().getId());
        }
        return dto;
    }



//-----User cases (actions):--------

    //1. CREATE:
    @Transactional
    public void saveApplication(ApplicationDto dto) {
        applicationRepository.save(toEntity(dto));
    }


    //2. READ - get all applications:
    public List<ApplicationDto> getAll() {
        //Define sorting criteria (createdAt field - descending order)
        Sort sort = Sort.by(Sort.Direction.DESC, "createdAt");

        List<Application> applications = applicationRepository.findAll(sort);
        List<ApplicationDto> dtoList = new ArrayList<>();

        for (Application a : applications) {
            dtoList.add(toDto(a));
        }

        return dtoList;
    }

}
