package com.hogar.seguro.service;

import com.hogar.seguro.dto.DonationDto;
import com.hogar.seguro.model.Donation;
import com.hogar.seguro.repository.DonationRepository;
import jakarta.transaction.Transactional;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Service
public class DonationService {

    private final DonationRepository donationRepository;

    public DonationService(DonationRepository donationRepository) {
        this.donationRepository = donationRepository;
    }


//-------Mapping Logic:----------------

    //1. DTO -> Entity
    public Donation toEntity(DonationDto dto) {
        Donation donation = new Donation();
        donation.setName(dto.getName());
        donation.setEmail(dto.getEmail());
        donation.setAmount(dto.getAmount());
        donation.setMessage(dto.getMessage());
        donation.setDate(LocalDateTime.now());//generated by system
        return donation;
    }


    //2. Entity -> DTO
    public DonationDto toDto(Donation donation) {
        DonationDto dto = new DonationDto();
        dto.setId(donation.getId());
        dto.setName(donation.getName());
        dto.setEmail(donation.getEmail());
        dto.setAmount(donation.getAmount());
        dto.setMessage(donation.getMessage());
        dto.setDate(donation.getDate()); //for admin
        return dto;
    }



//-----User cases (actions):------

    //1. CREATE
    @Transactional
    public void saveDonation(DonationDto dto) {
        donationRepository.save(toEntity(dto));
    }


    //2. READ
    public BigDecimal getTotalDonations() {
        BigDecimal total = donationRepository.sumAllDonations();
        return (total != null) ? total : BigDecimal.ZERO;
    }


    //3. READ  - Get All Donations (for admin)
    public List<DonationDto> getAll() {
        //Define sorting criteria (date field - descending order)
        Sort sort = Sort.by(Sort.Direction.DESC, "date");

        List<Donation> donations = donationRepository.findAll(sort);
        List<DonationDto> dtoList = new ArrayList<>();

        for (Donation d : donations) {
            dtoList.add(toDto(d));
        }

        return dtoList;
    }


}
