package com.hogar.seguro.service;


import com.hogar.seguro.dto.ApplicationDto;
import com.hogar.seguro.exception.ResourceNotFoundException;
import com.hogar.seguro.model.Application;
import com.hogar.seguro.model.Resident;
import com.hogar.seguro.model.enums.ApplicationType;
import com.hogar.seguro.repository.ApplicationRepository;
import com.hogar.seguro.repository.ResidentRepository;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.Sort;
import org.springframework.test.util.ReflectionTestUtils;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;


@ExtendWith(MockitoExtension.class)
@DisplayName("ApplicationService Tests")
public class ApplicationServiceTest {


    @Mock
    private ApplicationRepository applicationRepository;

    @Mock
    private ResidentRepository residentRepository;

    @InjectMocks
    private ApplicationService applicationService;


// ========================================================================
// 1. Mapping tests - toEntity() & toDto()
// ========================================================================


//--------------1.1 toEntity():

    //a) -> base mapping (simple fields)(VOLUNTARIADO case)
    @Test
    @DisplayName("Should map all basic fields from DTO to Entity when no residentId is provided")
    void shouldMapBasicFieldsWithoutResident() {

        // arrange
        ApplicationDto dto = new ApplicationDto();
        dto.setName("Carlos");
        dto.setEmail("carlos@mail.com");
        dto.setPhoneNumber("12345678");
        dto.setMessage("Quiero ayudar");
        dto.setApplicationType(ApplicationType.VOLUNTARIADO);

        // act
        Application application = applicationService.toEntity(dto);

        // assert
        assertAll("Verification of basic fields mapping",
                () -> assertNotNull(application, "The generated entity should not be null"),
                () -> assertEquals(dto.getName(), application.getName()),
                () -> assertEquals(dto.getEmail(), application.getEmail()),
                () -> assertEquals(dto.getPhoneNumber(), application.getPhoneNumber()),
                () -> assertEquals(dto.getMessage(), application.getMessage()),
                () -> assertEquals(ApplicationType.VOLUNTARIADO, application.getType()),
                () -> assertNotNull(application.getCreatedAt(), "createdAt should be generated by the system"),
                () -> assertNull(application.getResident(), "Resident should be null when no residentId is provided (volunteering case)")
        );

        verifyNoInteractions(residentRepository);
    }


    //b) -> Relationship mapping - residentId from dto present and valid (AMADRINAR or ADOPTAR case)
    @Test
    @DisplayName("Should map Resident when residentId is provided and exists")
    void shouldMapResidentWhenResidentIdExists() {
        // arrange
        Long residentId = 1L;

        ApplicationDto dto = new ApplicationDto();
        dto.setName("Carlos");
        dto.setEmail("carlos@mail.com");
        dto.setPhoneNumber("12345678");
        dto.setMessage("Quiero adoptar");
        dto.setApplicationType(ApplicationType.ADOPTAR);
        dto.setResidentId(residentId);

        Resident existingResident = new Resident();

        when(residentRepository.findByIdAndActiveTrue(residentId)).thenReturn(Optional.of(existingResident));

        // act
        Application application = applicationService.toEntity(dto);

        //assert
        assertAll("Verification of resident relationship mapping",
                () -> assertNotNull(application.getResident(), "Resident should be linked"),
                () -> assertEquals(existingResident, application.getResident()),
                () -> assertNotNull(application.getCreatedAt(), "createdAt should be generated")
        );

        verify(residentRepository).findByIdAndActiveTrue(residentId);
    }


    //b) Relationship mapping - residentId present but NOT found (exception)(AMADRINAR or ADOPTAR case)
    @Test
    @DisplayName("Should throw exception when residentId is provided but Resident does not exist")
    void shouldThrowExceptionWhenResidentNotFound() {
        // arrange
        Long residentId = 99L;

        ApplicationDto dto = new ApplicationDto();
        dto.setName("Carlos");
        dto.setEmail("carlos@mail.com");
        dto.setPhoneNumber("12345678");
        dto.setMessage("Quiero amadrinar");
        dto.setApplicationType(ApplicationType.AMADRINAR);
        dto.setResidentId(residentId);

        when(residentRepository.findByIdAndActiveTrue(residentId)).thenReturn(Optional.empty());

        //act & assert
        ResourceNotFoundException ex = assertThrows(ResourceNotFoundException.class, () -> {
            applicationService.toEntity(dto);
        }, "Expected ResourceNotFoundException to be thrown, but it was not");

        //extra assert
        assertEquals("Resident with id " + dto.getResidentId() + " not found.", ex.getMessage(),  "Exception messages do not match");
        verify(residentRepository).findByIdAndActiveTrue(residentId);
    }


//-------1.2 toDto():

    //a) -> base mapping (simple fields)(VOLUNTARIADO case)
    @Test
    @DisplayName("Should map all basic fields from Entity to DTO when no Resident is linked")
    void shouldMapBasicFieldsToDtoWithoutResident() {

        // arrange
        Application application = new Application();
        application.setName("Maripaz");
        application.setEmail("maripaz@mail.com");
        application.setPhoneNumber("12333443");
        application.setMessage("Quisiera apoyarlos");
        application.setType(ApplicationType.VOLUNTARIADO);
        application.setCreatedAt(LocalDateTime.now());
            // *resident intentionally null

        //act
        ApplicationDto dto = applicationService.toDto(application);

        //assert
        assertAll("Verificaction of basic DTO mapping",
                () -> assertNotNull(dto, "Generated dto should not be null"),
                () -> assertEquals(application.getName(), dto.getName()),
                () -> assertEquals(application.getEmail(), dto.getEmail()),
                () -> assertEquals(application.getPhoneNumber(), dto.getPhoneNumber()),
                () -> assertEquals(application.getMessage(), dto.getMessage()),
                () -> assertEquals(ApplicationType.VOLUNTARIADO, dto.getApplicationType()),
                () -> assertEquals(application.getCreatedAt(), dto.getCreatedAt()),
                () -> assertNull(dto.getResidentId(), "residentId should be null when no Resident is linked")
        );
    }


    //b) -> Relationship mapping - resident field from entity is present and valid (AMADRINAR or ADOPTAR case)
    @Test
    @DisplayName("Should set residentId in DTO when Resident is linked to the Entity")
    void shouldMapResidentIdWhenResidentExists() {
        // arrange
        Resident resident = new Resident();

        Application application = new Application();
        ReflectionTestUtils.setField(resident, "id", 1L);
        application.setName("Ariana");
        application.setEmail("ariana@mail.com");
        application.setPhoneNumber("123456799");
        application.setMessage("Me gustaría adoptar");
        application.setType(ApplicationType.ADOPTAR);
        application.setCreatedAt(LocalDateTime.now());
        application.setResident(resident);//entity with  resident field(relationship)

        //act
        ApplicationDto dto = applicationService.toDto(application);

        //assert
        assertNotNull(dto.getResidentId(), "residentId should not be null");

    }


// ========================================================================
// 2. CRUD Tests - (create) - saveApplication()
// ========================================================================

    @Test
    @DisplayName("Should save an application correctly")
    void shouldSaveApplication() {
        // Arrange
        ApplicationDto dto = new ApplicationDto();
        dto.setName("Sol");
        dto.setEmail("sol@mail.com");
        dto.setPhoneNumber("22345673");
        dto.setMessage("Tengo muchas ganas de apoyar");
        dto.setApplicationType(ApplicationType.VOLUNTARIADO);//VOLUNTARIADO case (not requuiered resident Id field)

        // Act
        applicationService.saveApplication(dto);

        // Assert
        verify(applicationRepository, times(1)).save(any(Application.class));
    }


// ========================================================================
// 3. CRUD Tests - (read) - getAll()
// ========================================================================

    @Test
    @DisplayName("Should return all applications ordered by createdAt field")
    void shouldReturnAllApplicationsOrderedByCreatedAt() {
        //arrange
        Application olderApplication = new Application();
        olderApplication.setName("Old Application");
        olderApplication.setEmail("old@mail.com");
        olderApplication.setPhoneNumber("111111");
        olderApplication.setMessage("Old message");
        olderApplication.setType(ApplicationType.ADOPTAR);
        olderApplication.setCreatedAt(LocalDateTime.now().minusDays(1));

        Application newerApplication = new Application();
        newerApplication.setName("New Application");
        newerApplication.setEmail("new@mail.com");
        newerApplication.setPhoneNumber("222222");
        newerApplication.setMessage("New message");
        newerApplication.setType(ApplicationType.ADOPTAR);
        newerApplication.setCreatedAt(LocalDateTime.now());

        List<Application> applicationList = List.of(newerApplication, olderApplication);

        when(applicationRepository.findAll(any(Sort.class))).thenReturn(applicationList);

        // act
        List<ApplicationDto> dtoList = applicationService.getAll();

        //assert
        assertAll("Verification of ordered applications list",
                () -> assertEquals(2, dtoList.size(), "List size should be 2"),
                () -> assertEquals("New Application", dtoList.get(0).getName(), "First element should be the most recent application"),
                () -> verify(applicationRepository).findAll(any(Sort.class))
        );

    }


}
