package com.hogar.seguro.dto;

import com.hogar.seguro.model.enums.ApplicationType;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

public class ApplicationDto {

    public ApplicationDto() {}

    private Long id;

    @NotBlank(message = "El nombre es obligatorio")
    @Size(max = 100)
    private String name;

    @NotBlank(message = "El email es obligatorio")
    @Email(message = "Debe ser un email válido")
    private String email;

    @NotBlank(message = "El teléfono es obligatorio") @Size(max = 20)
    private String phoneNumber;

    @NotBlank @Size(max = 2000)
    private String message;

    @NotNull(message = "El tipo de solicitud solicitada es requerida")
    private ApplicationType applicationType; //ADOPTAR, AMADRINAR, VOLUNTARIADO

    private Long residentId;//AMADRINAR /ADOPTAR cases

    private LocalDateTime createdAt;//generated by system(service)


//---Getters & Setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public String getPhoneNumber() { return phoneNumber; }
    public void setPhoneNumber(String phoneNumber) { this.phoneNumber = phoneNumber; }

    public String getMessage() { return message; }
    public void setMessage(String message) { this.message = message; }

    public ApplicationType getApplicationType() { return applicationType; }
    public void setApplicationType(ApplicationType applicationType) { this.applicationType = applicationType; }

    public Long getResidentId() { return residentId; }
    public void setResidentId(Long residentId) { this.residentId = residentId; }


    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }


    @Override public String toString() {
        return "Application{name='" + name + "', applicationType=" + applicationType +
                ", residentId=" + residentId + "}";
    }

}
