package com.hogar.seguro.dto;

import jakarta.validation.constraints.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

public class DonationDto {

    public DonationDto() {}

    private Long id;

    @NotBlank(message = "El nombre es obligatorio")
    @Size(max = 100)
    private String name;

    @NotBlank(message = "El email es obligatorio")
    @Email(message = "Debe ser un email válido")
    @Size(max = 150)
    private String email;

    @NotNull(message = "El monto es obligatorio")
    @DecimalMin(value = "1.00", message = "La donación mínima es de $1.00")
    @Digits(integer = 8, fraction = 2)
    private BigDecimal amount;

    @Size(max = 500)
    private String message;

    private LocalDateTime date;//generated by system(service)


//---Getters & Setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public BigDecimal getAmount() { return amount; }
    public void setAmount(BigDecimal amount) { this.amount = amount; }

    public String getMessage() { return message; }
    public void setMessage(String message) { this.message = message; }

    public LocalDateTime getDate() { return date; }
    public void setDate(LocalDateTime date) { this.date = date; }


    @Override public String toString() {
        return "Donor{name='" + name + "', amount=" + amount + "}";
    }

}
